### PR TITLE
Allow length greater than 10m

### LINKED ISSUE #10: Can't  run example with Beam equal or greater than 10m
Hi, thanks for this awesome package!

If I run the example code with Beam length equal or greater than 10:

```python
import os
from beambending import Beam, DistributedLoadV, PointLoadH, PointLoadV, x

def example_1():
    """Run example 1"""
    
    # <<< ONLY CHANGE >>>
    beam = Beam(10)  # Initialize a Beam object of length 9 m
    # <<< ONLY CHANGE >>>
    
    beam.pinned_support = 2    # x-coordinate of the pinned support
    beam.rolling_support = 7  # x-coordinate of the rolling support
    beam.add_loads((
                    PointLoadH(10, 3),  # 10 kN pointing right, at x=3 m
                    PointLoadV(-20, 3),  # 20 kN downwards, at x=3 m
                    DistributedLoadV(-10, (3, 9)),  # 10 kN/m, downwards, for 3 m <= x <= 9 m
                    DistributedLoadV(-20 + x**2, (0, 2)),  # variable load, for 0 <= x <= 2 m
                ))
    fig = beam.plot()

    # save the png and add it to the documentation
    mod_path = os.path.dirname(os.path.abspath(__file__))  # current module
    save_name = os.path.basename(__file__).replace('.py', '.png')  # file name
    save_path = os.path.join(mod_path, save_name)
    fig.savefig(save_path, transparent=True)


if __name__ == '__main__':  # call function when run as script
    example_1()
```

I get the following error:

```shell
Traceback (most recent call last):
  File "/Users/pedrober/.local/share/virtualenvs/pontes/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "diagrams.py", line 28, in <module>
    example_1()
  File "diagrams.py", line 18, in example_1
    fig = beam.plot()
  File "/Users/pedrober/.local/share/virtualenvs/pontes/lib/python3.7/site-packages/beambending/beam.py", line 229, in plot
    self.plot_beam_diagram(ax1)
  File "/Users/pedrober/.local/share/virtualenvs/pontes/lib/python3.7/site-packages/beambending/beam.py", line 252, in plot_beam_diagram
    self._plot_analytical(ax, sum(self._distributed_forces_y), **plot01_params)
  File "/Users/pedrober/.local/share/virtualenvs/pontes/lib/python3.7/site-packages/beambending/beam.py", line 307, in _plot_analytical
    x_vec = np.linspace(self._x0, self._x1, min(int((self.length) * 1000 + 1), 1e4))
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/pedrober/.local/share/virtualenvs/pontes/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

If I try to plot each figure instead of plotting all together, I get the same error.

### PR DESCRIPTION
**Pull request by PedroBern**
Fix #10

### CODE REVIEW

**Comment by PedroBern** [comment]
Hi @alfredocarella, thanks for the kind words.  Now I understand the reason of the limit. However, the suggestion you made is exactly what it was before, will limit to 10m. Could we keep at 100m? I can change to:

```diff
---  x_vec = np.linspace(self._x0, self._x1, int(min((self.length) * 1000 + 1), 1e4))
+++  x_vec = np.linspace(self._x0, self._x1, min(int((self.length) * 1000 + 1), 1e5))
```

Would it be ok? I agree that not having a limit is not ideal (as I initially proposed).

About the new example, is there something you would like me to change? The numbers were quite random.

**Comment by alfredocarella** [comment]
Sorry @PedroBern, I made a mistake with the parenthesis in my suggestion. Let me try to be more precise:

 ORIGINAL CODE (with bug):
`x_vec = np.linspace(self._x0, self._x1, min(int((self.length) * 1000 + 1), 1e4))`
When length exceeds 10m, the value 1e4 (float) is picked as the number of points in the graph, which is the source of the original error (1e4 should have been properly cast to an integer)

MY FIRST (incorrect) PROPOSAL:
`x_vec = np.linspace(self._x0, self._x1, int(min((self.length) * 1000 + 1), 1e4))`
There is one misplaced parenthesis (plus one too many)

A POTENTIAL FIX:
`x_vec = np.linspace(self._x0, self._x1, int(min(self.length * 1000 + 1, 1e4)))`
Notice that `int()` and `min()` swap places compared to the original. When length exceeds 10m, the value 1e4 is cast to integer and picked as the number of points in the graph, thereby limiting an arbitrarily high number of points while lengths over 10m are allowed.
10k points should result in more than enough resolution for any weird curve IMO.

**Comment by PedroBern** [comment]
I was misunderstanding the code. Now I see that x_vex is about the resolution, not the actual length! My bad. Thanks for explaining to me.

Ok, Already did the changes locally, it is passing the tests, but before I send the PR, about the example 4, would you like me to change something?

**Comment by alfredocarella** [comment]
I think example 4 is ok. You can leave it as is, or remove it if you don't believe it adds much information on top of example 1. I can accept both options, so I will leave it up to you.

**Pull request merged**
